ipfs-force-community/sophon-messager

models/mysql/shared_params.go
models/sqlite/shared_params.go
service/message_selector.go
service/shared_params_service.go
types/shared_params.go

change maxfee/maxfeecap fileld type in db to avoid overflow value

change maxfee/feecap filed type

---

gateway/gateway_client.go

issue: https://github.com/filecoin-project/venus/issues/4876

fix: Optimize the error log output when the gateway connection fails

---

Makefile
dockerfile

change to build docker image from local repo rather than from git chech out

fix: venus-messager : change to  build docker image from local repo 

---

dockerfile

fix https://github.com/filecoin-project/venus/issues/4999
update dependencies of ddl from base docker image

fix #4999 : venus-messager : update dependencies of ddl

---

docs/en/getting-started.md
docs/zh/design-specs.md
docs/zh/快速上手.md

fix https://github.com/filecoin-project/venus/issues/5019

docs: migrate from venus-docs

---

api/messager_impl.go
service/message_service.go

resolve https://github.com/filecoin-project/venus/issues/4861

feat:replace命令中maxfee支持fil单位

---

api/messager_impl.go
cli/address.go
cli/shared_params.go
go.mod
go.sum
models/address_test.go
models/mtypes/msg_meta.go
models/mysql/address.go
models/mysql/message.go
models/mysql/shared_params.go
models/repo/address_repo.go
models/shared_params_test.go
models/sqlite/address.go
models/sqlite/shared_params.go
service/address_service.go
service/message_selector.go
service/shared_params_service.go

resolve: https://github.com/filecoin-project/venus/issues/5044

feat: add gas over premium

---

.github/workflows/go.yml
.golangci.yml
api/jwt/jwt.go
api/modules.go
api/modules_test.go
cli/msg.go
cli/tablewriter/tablewriter.go
config/modules.go
gateway/gateway_client.go
main.go
metrics/trace.go
models/message_test.go
models/mysql/address.go
models/mysql/db.go
models/mysql/message.go
models/mysql/node.go
models/mysql/shared_params.go
models/sqlite/address.go
models/sqlite/message.go
models/sqlite/node.go
models/sqlite/shared_params.go
service/cache.go
service/message_selector.go
service/message_service.go
service/modules.go
utils/actor_parser/parser.go
utils/util.go

changes:
1. enable golang-cli-lint on git action.
2. pass golang-cli-lint checks.
3. remove duplicate `go test ...`
would resolve https://github.com/filecoin-project/venus/issues/5081

chore: git-action: enable golang-ci-lint checks on git action

---

.gitignore
Makefile
api/messager_impl.go
cli/address.go
cli/batch_replace.go
cli/cmd.go
cli/flag.go
cli/msg.go
cli/shared_params.go
cmds/client_example/main.go
config/modules.go
filestore/file_store.go
filestore/file_store_test.go
go.mod
go.sum
main.go
service/message_service.go
tools/config/config.go
tools/internal/batch_replace.go
tools/main.go
tools_config.toml
utils/util.go

resolve: https://github.com/filecoin-project/venus/issues/5039

feat: add batch replace cmd

---

models/mysql/message.go

resolve: https://github.com/filecoin-project/venus/issues/5094

fix: update the tipset_key field of the messages table to varchar(2048)

---

api/messager_impl.go
cli/shared_params.go
cmds/client_example/main.go
docs/zh/design-specs.md
go.mod
go.sum
models/address_test.go
models/mtypes/msg_meta.go
models/mysql/address.go
models/mysql/shared_params.go
models/repo/address_repo.go
models/shared_params_test.go
models/sqlite/address.go
models/sqlite/shared_params.go
service/address_service.go
service/message_selector.go
service/shared_params_service.go

resolve https://github.com/filecoin-project/venus/issues/4855

fix:支持gasfeecap配置/add gasfeecap

---

filestore/file_store.go
main.go
metrics/exporter.go

fix: https://github.com/filecoin-project/venus-messager/pull/220
修复 metric 配置不存在 时会panic

fix: metrics config is nil

---

go.mod
go.sum
version/version.go

resolve: https://github.com/filecoin-project/venus/issues/5059

chore: build v1.6.2

---

cli/msg.go
go.mod
go.sum
utils/convert_params.go
utils/convert_params_test.go

resolve: https://github.com/filecoin-project/venus/issues/5095

fix: fix incorrect output in cmd

---

api/modules.go
main.go
modules.go

resolve https://github.com/filecoin-project/venus/issues/5105

fix: support graceful shutdown

---

config/config.go
filestore/file_store.go
filestore/file_store_test.go
main.go

resolve https://github.com/filecoin-project/venus/issues/5128

cmd: remove config flag

---

Makefile
api/messager_impl.go
cli/cmd.go
cmds/client_example/main.go
gateway/gateway_client.go
go.mod
go.sum
main.go
service/address_service.go
service/message_selector.go
service/message_service.go
tools/internal/batch_replace.go
version/version.go

resolve https://github.com/filecoin-project/venus/issues/5132

feat: 增加Version接口/implement Version api

---

.github/workflows/build_upload.yml
.github/workflows/docker_image.yml
.github/workflows/go.yml

resolve https://github.com/filecoin-project/venus/issues/5002

ci: 拆分git工作流/split git workflow

---

go.mod
go.sum
models/mtypes/msg_meta.go
models/mysql/address.go
models/mysql/address_test.go
models/mysql/message.go
models/mysql/message_test.go
models/mysql/node.go
models/mysql/node_test.go
models/mysql/shared_params.go
models/mysql/shared_params_test.go
models/mysql/testing.go
models/sqlite/message.go
models/sqlite/message_test.go
models/sqlite/node.go
models/sqlite/shared_params.go
models/sqlite/shared_params_test.go

resolve https://github.com/filecoin-project/venus/issues/5167

feat: 补充MySQL相关单元测试/add unit test for mysql

---

cli/address.go
cli/shared_params.go
docs/en/getting-started.md
docs/zh/快速上手.md
go.mod
go.sum
service/address_service.go

fix: cmd: rename max-feecap to feecap

---

filestore/mock_file_store.go
gateway/mock_gateway_client.go
go.mod
go.sum
integration_test/address_test.go
integration_test/message_test.go
integration_test/mock_messager_server.go
integration_test/node_test.go
integration_test/shared_params_test.go
models/mysql/address_test.go
models/mysql/message.go
models/sqlite/address_test.go
pubsub/message_pubsub.go
service/message_service.go
service/shared_params_service.go
testhelper/full_node_server.go
testhelper/mock_data.go
testhelper/mock_full_node.go
testhelper/utils.go
testhelper/utils_test.go

resolve https://github.com/filecoin-project/venus/issues/5167

feat: 补充接口测试/add test for api

---

cmds/client_example/main.go
gateway/gateway_client.go
integration_test/mock_messager_server.go
main.go
pubsub/message_pubsub.go
pubsub/message_pubsub_test.go
service/address_service.go
service/message_service.go
service/message_state_refresh.go
service/modules.go
service/shared_params_service.go

resolve https://github.com/filecoin-project/venus/issues/5194

feat: 增加全局的context/add global context

---

go.mod
go.sum

close https://github.com/filecoin-project/venus/issues/5207

feat: use shared fullnode mock

---

gateway/mock_gateway_client.go
go.mod
go.sum
integration_test/message_test.go
integration_test/mock_messager_server.go
models/mysql/message.go
models/mysql/message_test.go
models/repo/message_repo.go
models/sqlite/message.go
models/sqlite/message_test.go
service/address_service.go
service/cache_test.go
service/message_selector_test.go
service/message_service.go
service/message_service_test.go
service/message_state_refresh.go
service/message_state_refresh_test.go
testhelper/mock_data.go
testhelper/mock_full_node.go
testhelper/utils.go

close https://github.com/filecoin-project/venus/issues/5209

test: 补充service模块的单元测试/add unit test for service

---

metrics/metrics.go
service/message_selector_test.go
service/message_service.go
service/message_state_refresh_test.go
testhelper/utils.go
utils/util.go
utils/util_test.go

opt: adjust some metrics

---

main.go

involve https://github.com/orgs/filecoin-project/projects/51/views/7
- add wait loop for chain height

fix: wait until node height bigger than zero

---

go.mod
go.sum
version/version.go

chore: bump version to v1.7.0

---

go.mod
go.sum
version/version.go

chore: bump version to v1.7.0 (#249)

---

service/shared_params_service.go

close https://github.com/filecoin-project/venus/issues/5266

opt: 全局的 maxfee 由 0.007FIL 调整为 0.07FIL / set default maxfee 0.07 FIL

---

Makefile

close https://github.com/filecoin-project/venus/issues/5267
rm deps and gen in makefile

fix: rm deps and gen in makefile

---

integration_test/address_test.go
service/message_service.go
service/message_state_refresh.go
service/message_state_refresh_test.go
testhelper/mock_full_node.go

close https://github.com/filecoin-project/venus/issues/5251

fix: 修复消息状态无法更新到正确的状态 / incorrect message state

---

integration_test/message_test.go
service/message_selector.go
service/message_selector_test.go
service/message_service.go
service/shared_params_service.go

resolve https://github.com/filecoin-project/venus/issues/5234

refactor: 移除对全局参数的缓存 / remove cached shared params

---

go.mod
metrics/metrics.go
service/message_service.go

fix: Metrics type & value err / 修复部分指标类型定义及赋值错误

---

cli/address.go

close https://github.com/filecoin-project/venus/issues/5277

fix: 修复未能正确设置选择消息数 / set incorrect sel msg num

---

config/config.go
filestore/file_store.go
filestore/file_store_test.go
service/message_selector.go

feat: request timeout configurable

---

config/config.go
log/log.go

fix filecoin-project/venus#5172

opt: Cancel the default log output file setting

---

service/events.go
service/message_selector_test.go
service/message_service.go
service/message_service_test.go
testhelper/mock_data.go
testhelper/mock_full_node.go

close https://github.com/filecoin-project/venus/issues/5375

fix: apply not correct when chain fork

---

service/message_selector.go

close https://github.com/filecoin-project/venus/issues/5353

fix: promote logLevel when nonceGap reach maxAllow

---

go.mod
go.sum
version/version.go

chore: bump version to v1.8.0-rc2

---

config/config.go
filestore/file_store.go
filestore/file_store_test.go
main.go
service/message_selector.go

feat: timeout configurable

---

docs/zh/metrics-使用说明.md

docs: add metric document

---

service/events.go

resolve https://github.com/filecoin-project/venus/issues/5331

fix: fix memory leak

---

models/mtypes/msg_meta.go
models/mysql/address.go
models/mysql/message.go
models/mysql/node.go
models/mysql/shared_params.go
models/repo/repo.go
models/sqlite/address.go
models/sqlite/message.go
models/sqlite/node.go

https://github.com/filecoin-project/venus/issues/5344
`meta_expire_epoch` `meta_gas_over_estimation`
`version` `nonce` `gas_limit` `method` `height` `state`
`receipt_gas_used`
`gas_over_estimation` `gas_over_premium`
`node_type`
`meta_max_fee` `value` `gas_fee_cap` `gas_premium`
`max_fee` `gas_fee_cap` `base_fee`

feat: set the default 0 for big.Int

---

go.mod
utils/convert_params.go
utils/convert_params_test.go

chore: opt convert params

---

cli/send.go
cli/util.go
go.mod
go.sum
models/mysql/message.go
models/sqlite/message.go
service/message_service.go

chore: reserve WalletName field of Messager type

---

config/config.go
go.mod
metrics/metrics.go
publisher/modules.go
publisher/publisher.go
publisher/publisher_test.go
publisher/pubsub/message_pubsub.go
service/message_selector.go
service/message_selector_test.go
service/message_service.go
service/message_service_test.go
service/message_state_refresh_test.go
utils/util.go
utils/util_test.go

resolve https://github.com/filecoin-project/venus/issues/5359

refactor: refactor message select

---

go.mod
go.sum
version/version.go

chore: bump version to v1.9.0-rc1

---

docs/zh/metrics-使用说明.md
metrics/metrics.go

https://github.com/filecoin-project/venus/issues/5488

chore: add jsonrpc metrics

---

integration_test/mock_messager_server.go
main.go

close https://github.com/filecoin-project/venus/issues/5404

chore: add check for WaitingChainHeadStableDuration

---

cli/flag.go

close https://github.com/filecoin-project/venus/issues/5568
--verbose 简化成 -v

feat: short for verbose

---

models/mysql/address_test.go
models/mysql/message.go
models/mysql/message_test.go
models/mysql/node_test.go
models/mysql/shared_params_test.go
models/mysql/testing.go
models/repo/message_repo.go
models/sqlite/message.go
models/sqlite/message_test.go
service/message_service.go
service/message_state_refresh.go
testhelper/mock_full_node.go

close https://github.com/filecoin-project/venus/issues/5589
1. replace 获取消息和更新加了事务
2. replace更新是附带了条件 状态必须是fill状态
3. 单元测试 改写了原来生成sql的方法

fix: replace cover on change message

---

cli/msg.go

resolve https://github.com/filecoin-project/venus/issues/5616

fix: unable to batch mark messages

---

cli/util.go
service/message_selector.go

fix: add ErrorMsg into msg output struct / 将错误信息加入到消息的输出类型中

---

go.mod
go.sum

chore: upgrade venus-related ref version to v1.9.0

---

.github/workflows/go.yml
main.go

fix: default value of WaitingChainHeadStableDuration

---

cli/msg.go
docs/zh/design-specs.md
go.mod
go.sum
service/message_service.go
service/message_state_refresh.go
service/message_state_refresh_test.go

close https://github.com/filecoin-project/venus/issues/5612

feat: rename replacedmsg to nonceconfict

---

models/mysql/message.go
models/mysql/message_test.go
models/sqlite/message.go
models/sqlite/message_test.go

close https://github.com/filecoin-project/venus/issues/5675

fix: query unchain message order by desc

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump version to v1.10.0-rc3

---

config/config.go
go.mod
go.sum
main.go

ref https://github.com/filecoin-project/venus/issues/4870

feat: update the authClient with token

---

publisher/publisher.go

chore: add address to error message

---

CHANGELOG.md
Makefile
go.mod
go.sum
version/version.go

chore: bump version to v1.10.0

---

api/messager_impl.go
main.go
service/message_selector.go

fix: fix delegated message

---

utils/convert_params.go
utils/convert_params_test.go

chore: optimize ETH address output

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump version to v1.10.1

---

models/mysql/actor_cfg.go

close https://github.com/filecoin-project/venus/issues/5822

fix: failed create actor_cfg table in mysql

---

api/messager_impl.go
integration_test/message_test.go
models/mysql/message.go
models/mysql/message_test.go
models/repo/message_repo.go
models/sqlite/message.go
models/sqlite/message_test.go

close https://github.com/filecoin-project/venus/issues/5848

feat: ListBlockedMessage interface also returns unfill message

---

CHANGELOG.md
version/version.go

chore: bump version to v1.10.2

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump up version to v1.11.0

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: merge Release/v1.11 into master

---

service/events.go
service/message_selector.go
service/message_service.go
service/message_service_test.go
service/message_state_refresh.go
testhelper/mock_full_node.go

close https://github.com/filecoin-project/venus/issues/5917

fix: repeat process msg

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump version to v1.12.0-rc1

---

api/messager_impl.go
cli/msg.go

close filecoin-project/venus#5976

feat(cmds): add update message state cmd

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump up version to v1.13.0

---

go.mod
go.sum

chore: update venus

---

CHANGELOG.md
version/version.go

chore: bump version to v1.14.0-rc2

---

CHANGELOG.md
go.mod
go.sum
service/message_service.go
version/version.go

chore: bump version to v1.14.0-rc3

---

.github/workflows/go.yml
integration_test/message_test.go
publisher/modules.go
publisher/publisher.go
publisher/publisher_test.go
service/message_service_test.go

close https://github.com/filecoin-project/venus/issues/6222

feat: record push message error info to db

---

cli/cmd.go
main.go

close https://github.com/filecoin-project/venus/issues/6068

chore: add repo evn var

---

service/message_selector.go

opt: reduce estimated messages

---

config/config.go

feat: reset msg estimating timeout to 30s

---

service/message_selector.go
service/message_selector_test.go

fix: check gas limit

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump version to v1.15.0

---

publisher/publisher.go

close https://github.com/filecoin-project/venus/issues/6342

fix: ignore invalid error message

---

version/version.go

chore: bump version to v1.17.1

---

go.mod
go.sum
version/version.go

chore: bump version to 1.18.0
