.gitignore, config/config.go, main.go, metrics/trace.go
support export traces to jaeger
=> support export traces to jaeger

.github/workflows/build_upload.yml
fix: git-action: mission colon in auto release workflow
=> fix: git-action: mission colon in auto release workflow

api/messager_impl.go, cli/address.go, cli/shared_params.go, go.mod, go.sum, integration_test/address_test.go, integration_test/message_test.go, integration_test/shared_params_test.go, models/mysql/address.go, models/mysql/address_test.go, models/mysql/shared_params.go, models/mysql/shared_params_test.go, models/repo/address_repo.go, models/sqlite/address.go, models/sqlite/address_test.go, models/sqlite/shared_params.go, models/sqlite/shared_params_test.go, models/sqlite/testing.go, service/address_service.go, service/message_selector.go, service/message_selector_test.go, service/message_service.go, service/shared_params_service.go, testhelper/mock_data.go, testhelper/mock_full_node.go
close https://github.com/filecoin-project/venus/issues/5139
=> feat:  选择符合低basefee条件消息进行推送 / support base fee

service/message_selector.go, service/message_selector_test.go, service/message_service.go, service/message_service_test.go, service/message_state_refresh_test.go, service/message_state_test.go
close filecoin-project/venus/issues/5273
feat: adding testing annotations for STM catalogs
=> feat: add testing annotations for STM

go.mod, go.sum, version/version.go
=> chore: bump to version v1.8.0-rc3

cli/address.go, cli/flag.go, cli/msg.go, cli/util.go
=> chore: Print the string associated with the message method

.circleci/config.yml
sub task of: https://github.com/filecoin-project/venus/issues/5220
circleci tests for STM enhancement
=> feat: circleci tests for STM enhancement

publisher/publisher.go, publisher/publisher_test.go, testhelper/mock_full_node.go
close https://github.com/filecoin-project/venus/issues/5662
使用MpoolBatchPushUntrusted替换MpoolBatchPush接口， 这样节点就不会保存消息，这样不会导致节点启动前的一段时间不同步的问题。
=> feat: use untrust api to avoid daemon save messages

.golangci.yml, service/cache_test.go, service/message_selector_test.go, service/message_service_test.go, service/message_state_refresh_test.go, service/node_service_test.go, testhelper/mock_data.go
=> test: remove duplicate code

api/modules.go, config/config.go, go.mod, go.sum, main.go
=> feat: add status api to detect api ready

api/messager_impl.go
=> fix: resolve address before check permission

service/message_service.go
close
replace 消息时没有使用 actor config 表中的 maxfee
=> fix: No actor configuration was used when replacing messages

service/message_selector.go
=> chore: more detailed error information

go.mod, go.sum, service/message_selector.go, service/message_service.go, service/message_service_test.go, testhelper/mock_full_node.go
close https://github.com/filecoin-project/venus/issues/5816
=> feat: Reduce minimum replace fee from 1.25x to 1.1x

integration_test/message_test.go, models/mysql/actor_cfg.go, models/mysql/actor_cfg_test.go, models/repo/actor_cfg_repo.go, models/sqlite/actor_cfg.go, models/sqlite/actor_cfg_test.go, service/message_selector.go
close https://github.com/filecoin-project/venus/issues/5939
=> feat: add HasActorCfg method

docs/zh/config-desc.md
=> annotate a configuration file using comments in toml format / toml注释的格式进行参数说明

main.go
close https://github.com/filecoin-project/venus/issues/6048
=> fix: not update token when http port already bind

CHANGELOG.md, go.mod, go.sum, models/sqlite/address_test.go, testhelper/mock_data.go, utils/convert_params_test.go, version/version.go
=> chore: bump version to v1.14.0

api/messager_impl.go, cli/msg.go, go.mod, go.sum, integration_test/message_test.go, models/mysql/message.go, models/mysql/message_test.go, models/repo/message_repo.go, models/sqlite/message.go, models/sqlite/message_test.go, service/message_service.go
close https://github.com/filecoin-project/venus/issues/6172
=> opt: add time flag for msg list command

api/messager_impl.go, cli/msg.go, cli/send.go, gateway/mock_gateway_client.go, integration_test/address_test.go, integration_test/message_test.go, models/mysql/actor_cfg.go, models/mysql/address.go, models/mysql/shared_params.go, models/sqlite/actor_cfg.go, models/sqlite/address.go, models/sqlite/shared_params.go, publisher/publisher.go, publisher/pubsub/message_pubsub.go, service/message_service.go, service/message_service_test.go, service/message_state_refresh.go, service/node_service.go, testhelper/mock_authclient.go, testhelper/mock_full_node.go
=> chore: fix lint
